### ISSUE TITLE
[app] unhandled exception error response logging is 128936712893712893712893617236712^2 lines long

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/console#594]
I need to scroll way too much here... Nobody cares about symbols and underscores and shit

```
SessionError: INVALID_CLAIMS
    at Session.<anonymous> (/app/node_modules/supertokens-node/lib/build/recipe/session/sessionClass.js:146:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/supertokens-node/lib/build/recipe/session/sessionClass.js:15:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'INVALID_CLAIMS',
  payload: [ { id: 'st-ev', reason: [Object] } ],
  errMagic: 'ndskajfasndlfkj435234krjdsa',
  fromRecipe: 'session'
}
{
  err: SessionError: INVALID_CLAIMS
      at Session.<anonymous> (/app/node_modules/supertokens-node/lib/build/recipe/session/sessionClass.js:146:27)
      at Generator.next (<anonymous>)
      at fulfilled (/app/node_modules/supertokens-node/lib/build/recipe/session/sessionClass.js:15:36)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    type: 'INVALID_CLAIMS',
    payload: [ [Object] ],
    errMagic: 'ndskajfasndlfkj435234krjdsa',
    fromRecipe: 'session'
  },
  req: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: null,
      ended: true,
      endEmitted: false,
      reading: false,
      constructed: true,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      setEncoding: [Function: socketSetEncoding],
      _paused: false,
      _httpMessage: [ServerResponse],
      [Symbol(async_id_symbol)]: 3996,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'host',
      'app.staging.graphql-hive.com',
      'cf-ipcountry',
      'DE',
      'cdn-loop',
      'cloudflare',
      'accept-encoding',
      'gzip',
      'x-forwarded-for',
      '2a02:8071:686:4a60:4db3:dcbb:e866:f477,172.70.246.88',
      'cf-ray',
      '764c1ce4887fbb9d-FRA',
      'x-forwarded-proto',
      'https',
      'cf-visitor',
      '{"scheme":"https"}',
      'sec-ch-ua',
      '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
      'sec-ch-ua-mobile',
      '?0',
      'sec-ch-ua-platform',
      '"macOS"',
      'dnt',
      '1',
      'upgrade-insecure-requests',
      '1',
      'user-agent',
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
      'accept',
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
      'sec-fetch-site',
      'none',
      'sec-fetch-mode',
      'navigate',
      'sec-fetch-user',
      '?1',
      'sec-fetch-dest',
      'document',
      'accept-language',
      'en-US,en-DE;q=0.9,en;q=0.8,ja-JP;q=0.7,ja;q=0.6,de;q=0.5',
      'cf-connecting-ip',
      '2a02:8071:686:4a60:4db3:dcbb:e866:f477',
      'cookie',
      '__stripe_mid=f1692855-6cd6-412e-82f3-c5a207c1bf90528365; crisp-client%2Fsession%2Faf9adec5-ddfa-4db9-a4a3-25769daf2fc2=session_57a531a5-1200-4dd2-bdba-557f384ac11d; ph_phc_Tbfg4EiRsr5iefFoth2Y1Hi3sttTeLQ5RV5TLg4hL1W_posthog=%7B%22distinct_id%22%3A%2218312bc328be71-050c4f440249f4-1a525635-4b9600-18312bc328c123b%22%2C%22%24device_id%22%3A%2218312bc328be71-050c4f440249f4-1a525635-4b9600-18312bc328c123b%22%2C%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%2C%22%24referrer%22%3A%22%24direct%22%2C%22%24referring_domain%22%3A%22%24direct%22%2C%22%24sesid%22%3A%5B1664457609396%2C%22183896790b4bbf-04cc6f4b746805-1a525635-4b9600-183896790b5e5f%22%2C1664457609396%5D%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24enabled_feature_flags%22%3A%7B%7D%7D; lastVisitedOrganization=laurinquast-382b; sIdRefreshToken=e7a18257-b542-414c-84f8-800ca456f243; sIRTFrontend=e7a18257-b542-414c-84f8-800ca456f243; sFrontToken=eyJ1aWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJhdGUiOjE2Njc1NTQyMTM4MzcsInVwIjp7InZlcnNpb24iOiIxIiwic3VwZXJUb2tlbnNVc2VySWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJleHRlcm5hbFVzZXJJZCI6bnVsbCwiZW1haWwiOiJsYXVyaW5xdWFzdEBnb29nbGVtYWlsLmNvbSJ9fQ==; sAccessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0%3D.eyJzZXNzaW9uSGFuZGxlIjoiOGE2NjcxOGMtMTJmZS00NDRjLThlMDUtNjUwNTA1MzE1YjUxIiwidXNlcklkIjoiOTViMjhhMjAtN2UxYS00MjA4LWE0ZTQtZDQ2NzY0MWRjMmMyIiwicmVmcmVzaFRva2VuSGFzaDEiOiI1YTE1MTljYzIyZDFhYjgxNzlmZGQ2M2ZlMDYyODcxNmM0MTZjZDY1YjAzMWJhOWY0OTc3YTNlZGNhYWRkNDYyIiwicGFyZW50UmVmcmVzaFRva2VuSGFzaDEiOm51bGwsInVzZXJEYXRhIjp7InZlcnNpb24iOiIxIiwic3VwZXJUb2tlbnNVc2VySWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJlbWFpbCI6ImxhdXJpbnF1YXN0QGdvb2dsZW1haWwuY29tIiwic3QtZXYiOnsidiI6ZmFsc2UsInQiOjE2Njc1NTA2NDM4NTB9fSwiYW50aUNzcmZUb2tlbiI6bnVsbCwiZXhwaXJ5VGltZSI6MTY2NzU1NDIxMzgzNywidGltZUNyZWF0ZWQiOjE2Njc1NTA2NDM4NjAsImxtcnQiOjE2Njc1NTA2NDM4NTN9.jX%2BDMnMWJp5P6qCL3bHlooc7GyOtmUTAOjyjvSTEQz8PsN%2FpUIuwbxHoUaWtr7atUvikmBzSewcqjKlwObsPq72TjRLPWUf3YrapkajbCskwco519Zy4AzBzeE3uik2w8sM6pw9M4VGNzBXXw0FcGZHYoyiJi%2BHfLKfC2vcsd0UhN%2FCZkGGU5pFAp50MqMFClCauwQfZPfWkodaGi1%2BIyUIn7xRG3U8mfoTgkN7VkA3lSPcDBvZnRvSeNyZ78DZRMdCBWkgznUIVp9hIUKgKQnZGKUbtk7f%2FQvRAeN1Ppt%2FaAwZpeXT3lU5NBPP7abeS%2BjpnW%2FPvkBNIwJCanUmd5A%3D%3D',
      'x-envoy-external-address',
      '172.70.246.88',
      'x-request-id',
      '663ad8d9-7ba3-49ea-b0cf-c845ec3ac81e',
      'x-envoy-expected-rq-timeout-ms',
      '15000',
      'x-request-start',
      't=1667551939.521'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '/',
    method: 'GET',
    statusCode: null,
    statusMessage: null,
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      setEncoding: [Function: socketSetEncoding],
      _paused: false,
      _httpMessage: [ServerResponse],
      [Symbol(async_id_symbol)]: 3996,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    cookies: {
      __stripe_mid: 'f1692855-6cd6-412e-82f3-c5a207c1bf90528365',
      'crisp-client%2Fsession%2Faf9adec5-ddfa-4db9-a4a3-25769daf2fc2': 'session_57a531a5-1200-4dd2-bdba-557f384ac11d',
      ph_phc_Tbfg4EiRsr5iefFoth2Y1Hi3sttTeLQ5RV5TLg4hL1W_posthog: '{"distinct_id":"18312bc328be71-050c4f440249f4-1a525635-4b9600-18312bc328c123b","$device_id":"18312bc328be71-050c4f440249f4-1a525635-4b9600-18312bc328c123b","$initial_referrer":"$direct","$initial_referring_domain":"$direct","$referrer":"$direct","$referring_domain":"$direct","$sesid":[1664457609396,"183896790b4bbf-04cc6f4b746805-1a525635-4b9600-183896790b5e5f",1664457609396],"$session_recording_enabled_server_side":false,"$active_feature_flags":[],"$enabled_feature_flags":{}}',
      lastVisitedOrganization: 'laurinquast-382b',
      sIdRefreshToken: 'e7a18257-b542-414c-84f8-800ca456f243',
      sIRTFrontend: 'e7a18257-b542-414c-84f8-800ca456f243',
      sFrontToken: 'eyJ1aWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJhdGUiOjE2Njc1NTQyMTM4MzcsInVwIjp7InZlcnNpb24iOiIxIiwic3VwZXJUb2tlbnNVc2VySWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJleHRlcm5hbFVzZXJJZCI6bnVsbCwiZW1haWwiOiJsYXVyaW5xdWFzdEBnb29nbGVtYWlsLmNvbSJ9fQ==',
      sAccessToken: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0=.eyJzZXNzaW9uSGFuZGxlIjoiOGE2NjcxOGMtMTJmZS00NDRjLThlMDUtNjUwNTA1MzE1YjUxIiwidXNlcklkIjoiOTViMjhhMjAtN2UxYS00MjA4LWE0ZTQtZDQ2NzY0MWRjMmMyIiwicmVmcmVzaFRva2VuSGFzaDEiOiI1YTE1MTljYzIyZDFhYjgxNzlmZGQ2M2ZlMDYyODcxNmM0MTZjZDY1YjAzMWJhOWY0OTc3YTNlZGNhYWRkNDYyIiwicGFyZW50UmVmcmVzaFRva2VuSGFzaDEiOm51bGwsInVzZXJEYXRhIjp7InZlcnNpb24iOiIxIiwic3VwZXJUb2tlbnNVc2VySWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJlbWFpbCI6ImxhdXJpbnF1YXN0QGdvb2dsZW1haWwuY29tIiwic3QtZXYiOnsidiI6ZmFsc2UsInQiOjE2Njc1NTA2NDM4NTB9fSwiYW50aUNzcmZUb2tlbiI6bnVsbCwiZXhwaXJ5VGltZSI6MTY2NzU1NDIxMzgzNywidGltZUNyZWF0ZWQiOjE2Njc1NTA2NDM4NjAsImxtcnQiOjE2Njc1NTA2NDM4NTN9.jX+DMnMWJp5P6qCL3bHlooc7GyOtmUTAOjyjvSTEQz8PsN/pUIuwbxHoUaWtr7atUvikmBzSewcqjKlwObsPq72TjRLPWUf3YrapkajbCskwco519Zy4AzBzeE3uik2w8sM6pw9M4VGNzBXXw0FcGZHYoyiJi+HfLKfC2vcsd0UhN/CZkGGU5pFAp50MqMFClCauwQfZPfWkodaGi1+IyUIn7xRG3U8mfoTgkN7VkA3lSPcDBvZnRvSeNyZ78DZRMdCBWkgznUIVp9hIUKgKQnZGKUbtk7f/QvRAeN1Ppt/aAwZpeXT3lU5NBPP7abeS+jpnW/PvkBNIwJCanUmd5A=='
    },
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      host: 'app.staging.graphql-hive.com',
      'cf-ipcountry': 'DE',
      'cdn-loop': 'cloudflare',
      'accept-encoding': 'gzip',
      'x-forwarded-for': '2a02:8071:686:4a60:4db3:dcbb:e866:f477,172.70.246.88',
      'cf-ray': '764c1ce4887fbb9d-FRA',
      'x-forwarded-proto': 'https',
      'cf-visitor': '{"scheme":"https"}',
      'sec-ch-ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      dnt: '1',
      'upgrade-insecure-requests': '1',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
      accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
      'sec-fetch-site': 'none',
      'sec-fetch-mode': 'navigate',
      'sec-fetch-user': '?1',
      'sec-fetch-dest': 'document',
      'accept-language': 'en-US,en-DE;q=0.9,en;q=0.8,ja-JP;q=0.7,ja;q=0.6,de;q=0.5',
      'cf-connecting-ip': '2a02:8071:686:4a60:4db3:dcbb:e866:f477',
      cookie: '__stripe_mid=f1692855-6cd6-412e-82f3-c5a207c1bf90528365; crisp-client%2Fsession%2Faf9adec5-ddfa-4db9-a4a3-25769daf2fc2=session_57a531a5-1200-4dd2-bdba-557f384ac11d; ph_phc_Tbfg4EiRsr5iefFoth2Y1Hi3sttTeLQ5RV5TLg4hL1W_posthog=%7B%22distinct_id%22%3A%2218312bc328be71-050c4f440249f4-1a525635-4b9600-18312bc328c123b%22%2C%22%24device_id%22%3A%2218312bc328be71-050c4f440249f4-1a525635-4b9600-18312bc328c123b%22%2C%22%24initial_referrer%22%3A%22%24direct%22%2C%22%24initial_referring_domain%22%3A%22%24direct%22%2C%22%24referrer%22%3A%22%24direct%22%2C%22%24referring_domain%22%3A%22%24direct%22%2C%22%24sesid%22%3A%5B1664457609396%2C%22183896790b4bbf-04cc6f4b746805-1a525635-4b9600-183896790b5e5f%22%2C1664457609396%5D%2C%22%24session_recording_enabled_server_side%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%2C%22%24enabled_feature_flags%22%3A%7B%7D%7D; lastVisitedOrganization=laurinquast-382b; sIdRefreshToken=e7a18257-b542-414c-84f8-800ca456f243; sIRTFrontend=e7a18257-b542-414c-84f8-800ca456f243; sFrontToken=eyJ1aWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJhdGUiOjE2Njc1NTQyMTM4MzcsInVwIjp7InZlcnNpb24iOiIxIiwic3VwZXJUb2tlbnNVc2VySWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJleHRlcm5hbFVzZXJJZCI6bnVsbCwiZW1haWwiOiJsYXVyaW5xdWFzdEBnb29nbGVtYWlsLmNvbSJ9fQ==; sAccessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0%3D.eyJzZXNzaW9uSGFuZGxlIjoiOGE2NjcxOGMtMTJmZS00NDRjLThlMDUtNjUwNTA1MzE1YjUxIiwidXNlcklkIjoiOTViMjhhMjAtN2UxYS00MjA4LWE0ZTQtZDQ2NzY0MWRjMmMyIiwicmVmcmVzaFRva2VuSGFzaDEiOiI1YTE1MTljYzIyZDFhYjgxNzlmZGQ2M2ZlMDYyODcxNmM0MTZjZDY1YjAzMWJhOWY0OTc3YTNlZGNhYWRkNDYyIiwicGFyZW50UmVmcmVzaFRva2VuSGFzaDEiOm51bGwsInVzZXJEYXRhIjp7InZlcnNpb24iOiIxIiwic3VwZXJUb2tlbnNVc2VySWQiOiI5NWIyOGEyMC03ZTFhLTQyMDgtYTRlNC1kNDY3NjQxZGMyYzIiLCJlbWFpbCI6ImxhdXJpbnF1YXN0QGdvb2dsZW1haWwuY29tIiwic3QtZXYiOnsidiI6ZmFsc2UsInQiOjE2Njc1NTA2NDM4NTB9fSwiYW50aUNzcmZUb2tlbiI6bnVsbCwiZXhwaXJ5VGltZSI6MTY2NzU1NDIxMzgzNywidGltZUNyZWF0ZWQiOjE2Njc1NTA2NDM4NjAsImxtcnQiOjE2Njc1NTA2NDM4NTN9.jX%2BDMnMWJp5P6qCL3bHlooc7GyOtmUTAOjyjvSTEQz8PsN%2FpUIuwbxHoUaWtr7atUvikmBzSewcqjKlwObsPq72TjRLPWUf3YrapkajbCskwco519Zy4AzBzeE3uik2w8sM6pw9M4VGNzBXXw0FcGZHYoyiJi%2BHfLKfC2vcsd0UhN%2FCZkGGU5pFAp50MqMFClCauwQfZPfWkodaGi1%2BIyUIn7xRG3U8mfoTgkN7VkA3lSPcDBvZnRvSeNyZ78DZRMdCBWkgznUIVp9hIUKgKQnZGKUbtk7f%2FQvRAeN1Ppt%2FaAwZpeXT3lU5NBPP7abeS%2BjpnW%2FPvkBNIwJCanUmd5A%3D%3D',
      'x-envoy-external-address': '172.70.246.88',
      'x-request-id': '663ad8d9-7ba3-49ea-b0cf-c845ec3ac81e',
      'x-envoy-expected-rq-timeout-ms': '15000',
      'x-request-start': 't=1667551939.521'
    },
    [Symbol(kHeadersCount)]: 52,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined,
    [Symbol(NextRequestMeta)]: {
      __NEXT_INIT_URL: 'http://localhost:3000/',
      __NEXT_INIT_QUERY: {},
      _protocol: 'http',
      __NEXT_CLONABLE_BODY: [Object],
      __nextHadTrailingSlash: false,
      __nextIsLocaleDomain: false
    }
  },
  res: <ref *1> ServerResponse {
    _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
    _eventsCount: 1,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: true,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: false,
    _headerSent: false,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Server],
      _server: [Server],
      parser: [HTTPParser],
      on: [Function: socketListenerWrap],
      addListener: [Function: socketListenerWrap],
      prependListener: [Function: socketListenerWrap],
      setEncoding: [Function: socketSetEncoding],
      _paused: false,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 3996,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: null,
    _keepAliveTimeout: 5000,
    _onPendingData: [Function: bound updateOutgoingData],
    req: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/',
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: false,
      cookies: [Object],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 52,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined,
      [Symbol(NextRequestMeta)]: [Object]
    },
    _sent100: false,
    _expect_continue: false,
    statusCode: 500,
    flush: [Function: flush],
    write: [Function: write],
    end: [Function: end],
    on: [Function: on],
    writeHead: [Function: writeHead],
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      'front-token': [Array],
      'access-control-expose-headers': [Array],
      'set-cookie': [Array]
    }
  },
  pathname: '/_error',
  query: {},
  asPath: '/',
  locale: undefined,
  locales: undefined,
  defaultLocale: undefined,
  AppTree: [Function: AppTree],
  defaultGetInitialProps: [AsyncFunction: defaultGetInitialProps]
}
```

**Comment by dotansimha** [comment]
@n1ru4l is it still an issue? is there anything we can do on our end? or it's coming from SuperTokens lib?

**Comment by n1ru4l** [comment]
It is how Next.js errors are logged in general
