### ISSUE TITLE
Error while configuring Slack integration 

### ISSUE THREAD

**Issue by rickbijkerk** [graphql-hive/console#6073]
Context:
- we're trying to connect hive to our slack
- with identical hive config and the same slackbot it did work on our staging environment
- trying to integrate with slack on our pro environment leads to the following error in the log:

<img width="701" alt="image" src="https://github.com/user-attachments/assets/f2628e17-f216-4b34-bf92-2cdd0fe71def">

```
GraphQLError: Variable "$input" got invalid value { organization: "my-organization" }; Field value.token of required type String! was not provided.
    at getVariables (eval at compileVariableParsing (file:///usr/src/app/@hive/server/index.js:249937:23), <anonymous>:44:23)
    at addSlackIntegration (file:///usr/src/app/@hive/server/index.js:250335:35)
    at ValueOrPromise.then.result.stringify (file:///usr/src/app/@hive/server/index.js:349701:37)
    at new ValueOrPromise (file:///usr/src/app/@hive/server/index.js:270170:15)
    at jitExecutor (file:///usr/src/app/@hive/server/index.js:349701:12)
    at file:///usr/src/app/@hive/server/index.js:349406:75
    at file:///usr/src/app/@hive/server/index.js:269844:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YogaServer.getResultForParams (file:///usr/src/app/@hive/server/index.js:275279:18)
    at async handle (file:///usr/src/app/@hive/server/index.js:275355:20)
    at async file:///usr/src/app/@hive/server/index.js:358390:24
    at async Object.<anonymous> (file:///usr/src/app/@hive/server/index.js:358387:5) {
  locations: [ { line: 1, column: 30 } ]
}
```

it looks like the https://slack.com/api/oauth.v2.access call does not get a token as a response?
i already double checked the INTEGRATION_SLACK_CLIENT_SECRET and its correct.
Any clue with it can be/experience with it?

Hive version: 10-sept-2024

**Comment by kamilkisiela** [comment]
Pushing this https://github.com/graphql-hive/console/pull/6261 to validate the response from Slack API and detect missing access_token field.

**Comment by rickbijkerk** [comment]
Hey i was on a holiday but after updating hive we do see more info, still not a 100% sure on the root cause.

Logs:
> Fetching data from Slack API (orgId=test)
> Failed to retrieve access token from Slack API (orgId=test)
> bad_redirect_uri
